// src/components/WFShowTicket/index.tsx
import { ComponentProps, ReactElement } from "react";
import "./index.scss";

const regexRemoveCommas = /.+(ESM-\d\d\d\d\d\d?).+/;

interface Props extends ComponentProps<"a"> {
  blockingTicket: string | null;
  jiraPath: string;
}

export default function WFShowTicket({
  blockingTicket,
  jiraPath,
  ...props
}: Readonly<Props>): ReactElement {
  if (!blockingTicket) {
    throw new Error("blocking ticket is null");
  }

  const blockingTicketReplaced = blockingTicket.replace(
    regexRemoveCommas,
    "$1",
  );
  return (
    <a
      {...props}
      className="showTicket"
      href={`https://${jiraPath}${blockingTicketReplaced}#view-subtasks`}
      target="_blank"
      rel="noreferrer"
    >
      {blockingTicket}
    </a>
  );
}

// src/lib/content/WFShowTicket.svelte
<script lang="ts">
  import { jiraFullPath } from "$lib/storage";
  import type { HTMLAnchorAttributes } from "svelte/elements";

  interface Props extends HTMLAnchorAttributes {
    blockingTicket: string;
  }

  const { blockingTicket, ...restProps }: Props = $props();

  const regexRemoveCommas = /.+(ESM-\d\d\d\d\d\d?).+/;

  const blockingTicketReplaced = blockingTicket.replace(
    regexRemoveCommas,
    "$1",
  );
</script>

<a
  {...restProps}
  class="showTicket"
  href="https://{jiraFullPath}{blockingTicketReplaced}#view-subtasks"
  target="_blank"
  rel="noreferrer"
>
  {blockingTicket}
</a>

<style lang="scss">
  a.showTicket {
    cursor: pointer;
    font-weight: 500;
    color: rgb(59 130 246);

    &:hover {
      text-decoration-line: underline;
    }
  }
</style>
