// src/pages/popup/Popup.tsx
import { ComponentProps, MouseEvent, ReactElement } from "react";
import { Async } from "react-async";
import { Alert, Button, Loading } from "react-daisyui";
import { FaCog, FaGithub } from "react-icons/fa";
import { UploadJsonFile } from "src/components";
import {
  getFullAuthorPath,
  getLocalSavedData,
  getRegexAuthor,
  ifAnyOfTheEnv,
  ifAuthor,
  ifAuthorNoEnv,
  ifClassic,
  ifJira,
  ifLive,
  ifPerf,
  ifProd,
  ifTouch,
} from "src/lib/storage";
import { findAsyncSequential, getCurrentTab } from "src/lib/tools";
import {
  ColorProps,
  EnvTypesExtended,
  MessageAlert,
  MessageEnv,
  SubjectTypes,
} from "src/lib/types";
import { runtime, tabs, Tabs, webNavigation } from "webextension-polyfill";
import { create } from "zustand";
import "./index.scss";

const regexCopyContent = /\/content.+(?=\.html)/;

let isFileUploaded = true;

interface AlertProps {
  text?: string;
  color?: ColorProps;
}

type BtnSubjectType =
  | "toEnvironment"
  | "createWF"
  | "openInTree"
  | "checkReferences"
  | "checkMothersite";

interface ButtonEnvType extends ComponentProps<typeof Button> {
  anyEnv: boolean;
  customEnv: boolean;
  butEnv?: EnvTypesExtended;
  butSubject?: BtnSubjectType;
  butSendAs?: "runtime" | "tab";
}

async function getPropertiesPath(): Promise<string> {
  const {
    secretSettings: { propertiesPath },
  } = await getLocalSavedData();
  return propertiesPath;
}

interface InitVariablesType {
  tabUrl: string;
  ifAnyOfTheEnvCache: boolean;
  ifAuthorCache: boolean;
  ifClassicCache: boolean;
  ifJiraCache: boolean;
  ifLiveCache: boolean;
  ifPerfCache: boolean;
  ifProdCache: boolean;
  ifTouchCache: boolean;
}

const useStateAlert = create<{
  alertProps: AlertProps | null;
  setAlertProps: (alertProps: AlertProps) => void;
}>((set) => ({
  alertProps: null,
  setAlertProps: ({ text, color }) =>
    set(() => ({ alertProps: { text, color } })),
}));

async function copyContent(url: string): Promise<void> {
  const content: string | undefined = regexCopyContent.exec(url)?.[0];
  if (!content) {
    throw new Error(`copied content is ${content}`);
  }

  navigator.clipboard.writeText(content);

  useStateAlert.setState({
    alertProps: { text: `${content} copied to clipboard`, color: "info" },
  });
}

function ButtonEnv({
  anyEnv,
  customEnv,
  ...props
}: Readonly<ButtonEnvType>): ReactElement {
  if (!anyEnv || customEnv) {
    return <></>;
  }

  return <Button {...props} />;
}

async function buttonOnClick({
  currentTarget,
  type,
}: MouseEvent<HTMLButtonElement>): Promise<void> {
  const sendAs = currentTarget.getAttribute("butsendas");
  if (!sendAs) {
    throw new Error("butsendas is undefined");
  }

  const activeTabs: Tabs.Tab[] = await tabs.query({
    highlighted: true,
    currentWindow: true,
  });

  let tabId = activeTabs[activeTabs.length - 1].id;
  if (!tabId) {
    throw new Error(`tabId is ${tabId}`);
  }

  const frames = await webNavigation.getAllFrames({ tabId });
  if (frames) {
    const conditionFound = await findAsyncSequential(frames, ({ url }) =>
      ifAuthorNoEnv(url),
    );

    if (conditionFound?.tabId) {
      tabId = conditionFound.tabId;
    }
  }

  const message: MessageEnv = {
    from: "popup",
    newTab: type !== "click",
    env: currentTarget.getAttribute("butenv") as EnvTypesExtended,
    subject: currentTarget.getAttribute("butsubject") as SubjectTypes,
    tabs: activeTabs,
  };

  if (sendAs === "tab") {
    tabs.sendMessage(tabId, message);
  } else {
    runtime.sendMessage(message);
  }
}

async function openPropertiesTouchUI(): Promise<void> {
  const { url, index }: Tabs.Tab = await getCurrentTab();
  const fullAuthorPath = await getFullAuthorPath();
  const propertiesPath = await getPropertiesPath();
  const regexAuthor = await getRegexAuthor();

  const newUrl = url?.replace(
    regexAuthor,
    `https://${fullAuthorPath}/${propertiesPath}`,
  );

  tabs.create({
    url: newUrl,
    index: index + 1,
  });
}

function setFileUploaded(): boolean {
  isFileUploaded = false;
  return isFileUploaded;
}

async function initVariables(): Promise<InitVariablesType> {
  const { url: tabUrl } = await getCurrentTab();
  if (!tabUrl) {
    throw new Error("url is undefined");
  }

  const ifAnyOfTheEnvCache = await ifAnyOfTheEnv(tabUrl).catch(setFileUploaded);
  const ifAuthorCache = await ifAuthor(tabUrl).catch(setFileUploaded);
  const ifClassicCache = await ifClassic(tabUrl).catch(setFileUploaded);
  const ifJiraCache = await ifJira(tabUrl).catch(setFileUploaded);
  const ifLiveCache = await ifLive(tabUrl).catch(setFileUploaded);
  const ifPerfCache = await ifPerf(tabUrl).catch(setFileUploaded);
  const ifProdCache = await ifProd(tabUrl).catch(setFileUploaded);
  const ifTouchCache = await ifTouch(tabUrl).catch(setFileUploaded);

  return {
    tabUrl,
    ifAnyOfTheEnvCache,
    ifAuthorCache,
    ifClassicCache,
    ifJiraCache,
    ifLiveCache,
    ifPerfCache,
    ifProdCache,
    ifTouchCache,
  };
}

runtime.onMessage.addListener(
  // @ts-expect-error types issue
  ({ from, color, message: text, subject }: MessageAlert) => {
    if (from === "popup") {
      return;
    }

    if (subject === "showMessage") {
      useStateAlert.setState({
        alertProps: { text, color },
      });
    }
  },
);

export default function Popup(): ReactElement {
  const { alertProps } = useStateAlert();

  return (
    <Async promiseFn={initVariables}>
      <Async.Pending>
        <div className="grid h-44 place-items-center">
          <Loading />
        </div>
      </Async.Pending>
      <Async.Fulfilled>
        {({
          tabUrl,
          ifAnyOfTheEnvCache,
          ifJiraCache,
          ifLiveCache,
          ifPerfCache,
          ifProdCache,
          ifTouchCache,
          ifClassicCache,
          ifAuthorCache,
        }: InitVariablesType) => (
          <div className="flex flex-col gap-5">
            {isFileUploaded ? (
              <>
                <div className="hidden place-content-center has-[button]:flex">
                  <ButtonEnv
                    anyEnv={true}
                    customEnv={!ifJiraCache}
                    butSubject="createWF"
                    butSendAs="tab"
                    size="md"
                    color="accent"
                    onClick={buttonOnClick}
                  >
                    Create WF
                  </ButtonEnv>
                </div>

                <div className="hidden place-content-center gap-2 has-[button]:flex">
                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={ifLiveCache}
                    butEnv="live"
                    butSubject="toEnvironment"
                    butSendAs="runtime"
                    size="md"
                    color="success"
                    onClick={buttonOnClick}
                    onAuxClick={buttonOnClick}
                  >
                    To Live
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={ifPerfCache}
                    butEnv="perf"
                    butSubject="toEnvironment"
                    butSendAs="runtime"
                    size="md"
                    color="info"
                    onClick={buttonOnClick}
                    onAuxClick={buttonOnClick}
                  >
                    To Perf
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={ifProdCache}
                    butEnv="prod"
                    butSubject="toEnvironment"
                    butSendAs="runtime"
                    size="md"
                    color="warning"
                    onClick={buttonOnClick}
                    onAuxClick={buttonOnClick}
                  >
                    To Prod
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={ifTouchCache}
                    butEnv={"editor.html"}
                    butSubject="toEnvironment"
                    butSendAs="runtime"
                    size="md"
                    color="accent"
                    onClick={buttonOnClick}
                    onAuxClick={buttonOnClick}
                  >
                    To Touch
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={ifClassicCache}
                    butEnv={"cf#"}
                    butSubject="toEnvironment"
                    butSendAs="runtime"
                    size="md"
                    color="error"
                    onClick={buttonOnClick}
                    onAuxClick={buttonOnClick}
                  >
                    To Classic
                  </ButtonEnv>
                </div>

                <div className="hidden flex-wrap place-content-center gap-2 has-[button]:flex">
                  <hr className="my-1 h-px w-full border-0 bg-gray-200" />
                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={!ifAuthorCache}
                    size="md"
                    color="secondary"
                    onClick={() => copyContent(tabUrl)}
                  >
                    Copy Content
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={!ifAuthorCache}
                    size="md"
                    color="accent"
                    onClick={openPropertiesTouchUI}
                  >
                    Open Properties Touch UI
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={!ifAuthorCache}
                    butSubject="openInTree"
                    butSendAs="runtime"
                    size="md"
                    color="success"
                    onClick={buttonOnClick}
                  >
                    Open In Tree
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={!ifAuthorCache}
                    butSubject="checkReferences"
                    butSendAs="tab"
                    size="md"
                    color="error"
                    onClick={buttonOnClick}
                  >
                    Check references
                  </ButtonEnv>

                  <ButtonEnv
                    anyEnv={ifAnyOfTheEnvCache}
                    customEnv={ifAuthorCache}
                    butSubject="checkMothersite"
                    butSendAs="tab"
                    size="md"
                    color="success"
                    onClick={buttonOnClick}
                  >
                    Check mothersite links
                  </ButtonEnv>
                </div>

                {alertProps && (
                  <Alert
                    className="animate-fade duration-75"
                    status={alertProps.color}
                  >
                    {alertProps.text}
                  </Alert>
                )}
              </>
            ) : (
              <UploadJsonFile />
            )}

            <div className="mt-auto flex place-content-between gap-2">
              <Button
                color="neutral"
                tag="a"
                href="/src/pages/options/index.html"
                size="sm"
              >
                <FaCog className="mr-2 h-5 w-5" />
                Options
              </Button>

              <Button
                color="neutral"
                tag="a"
                href="https://github.com/KovalchukDanil0/AEMFixes#features"
                target="_blank"
                size="sm"
              >
                <FaGithub className="mr-2 h-5 w-5" />
                See Guide
              </Button>
            </div>
          </div>
        )}
      </Async.Fulfilled>
      <Async.Rejected>
        {(error) => `Something went wrong: ${error.message}`}
      </Async.Rejected>
    </Async>
  );
}

// src/entrypoints/popup/Popup.svelte
<script lang="ts" module>
  import { Alert, ButtonEnv, Link, Spinner } from "$components";
  import { onMessage, sendMessage } from "$lib/messaging";
  import { fullAuthorPath, propertiesPath, regexAuthor } from "$lib/storage";
  import "$styles/main.css";
  import "@fontsource/open-sans";
  import ky from "ky";
  import { Icon } from "svelte-icons-pack";
  import { FaBrandsGithub, FaSolidWrench } from "svelte-icons-pack/fa";

  interface AlertType {
    text: string;
    color: ColorProps;
  }

  const [{ url, index: tabIndex, id: tabId, status }] =
    await browser.tabs.query({
      active: true,
      currentWindow: true,
    });

  let pageLoaded = $state(false);
  let environment: EnvTypes | null = $state(null);

  let alertBanner = $state<AlertType | null>(null);

  const setEnvironment = (env: EnvTypes) => (environment = env);

  async function fetchEnvironment(tabId: number) {
    environment = await sendMessage("getEnvironment", {}, tabId).catch(
      () => null,
    );
  }

  if (status === "complete" && tabId) {
    pageLoaded = true;
    await fetchEnvironment(tabId);
  }

  browser.tabs.onUpdated.addListener(async (updatedTabId, changeInfo) => {
    if (updatedTabId !== tabId) {
      return;
    }

    if (changeInfo.status === "complete") {
      // browser.tabs.onUpdated.removeListener(listener);
      pageLoaded = true;
      await fetchEnvironment(updatedTabId);
    }

    if (changeInfo.status === "loading") {
      pageLoaded = false;
    }
  });

  onMessage("showMessage", ({ data: { text, color } }) => {
    alertBanner = { text, color };
  });

  const regexCopyContent = /\/content.+(?=\.html)/;

  function copyContent() {
    if (!url) {
      return;
    }

    const [content] = regexCopyContent.exec(url) ?? "";
    if (!content) {
      throw new Error(`copied content is ${content}`);
    }

    navigator.clipboard.writeText(content);

    alertBanner = { text: `${content} copied to clipboard`, color: "info" };
  }

  function openPropertiesTouchUI() {
    const newUrl = url?.replace(
      regexAuthor,
      `https://${fullAuthorPath}/${propertiesPath}`,
    );

    browser.tabs.create({
      url: newUrl,
      index: tabIndex + 1,
    });
  }
</script>

<div class="flex size-full grow flex-col items-center justify-center gap-5">
  {#if !pageLoaded}
    <Spinner />
    {#await ky
      .get("https://thefact.space/random")
      .json<{ text: string }>() then { text: randomFact }}
      <p class="text-shadow-lg/20">{randomFact}</p>
    {/await}
  {:else if environment}
    {#if environment === "jira"}
      <div class="flex items-center justify-center">
        <ButtonEnv variant="red" btnSubject="createWF" btnSendAs="tab"
          >Create WF</ButtonEnv
        >
      </div>
    {:else}
      <div class="hidden items-center justify-center gap-2 has-[button]:flex">
        {#if environment !== "live"}
          <ButtonEnv
            variant="green"
            btnEnv="live"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Live
          </ButtonEnv>
        {/if}

        {#if environment !== "perf"}
          <ButtonEnv
            variant="sky"
            btnEnv="perf"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Perf
          </ButtonEnv>
        {/if}

        {#if environment !== "prod"}
          <ButtonEnv
            variant="orange"
            btnEnv="prod"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Prod
          </ButtonEnv>
        {/if}

        {#if environment !== "cf#"}
          <ButtonEnv
            variant="amber"
            btnEnv="cf#"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Classic
          </ButtonEnv>
        {/if}

        {#if environment !== "editor.html"}
          <ButtonEnv
            variant="teal"
            btnEnv="editor.html"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Touch
          </ButtonEnv>
        {/if}
      </div>

      <div
        class="hidden flex-wrap items-center justify-center gap-2 has-[button]:flex"
      >
        {#if environment === "cf#" || environment === "editor.html"}
          <ButtonEnv variant="yellow" onclick={copyContent}
            >Copy Content</ButtonEnv
          >

          <ButtonEnv variant="fuchsia" onclick={openPropertiesTouchUI}>
            Open Properties Touch UI
          </ButtonEnv>

          <ButtonEnv
            variant="violet"
            btnSubject="openInTree"
            btnSendAs="runtime"
          >
            Open In Tree
          </ButtonEnv>

          <ButtonEnv
            variant="lime"
            btnSubject="checkReferences"
            btnSendAs="tab"
          >
            Check references
          </ButtonEnv>
        {/if}

        {#if environment === "live" || environment === "perf" || environment === "prod"}
          <ButtonEnv
            variant="indigo"
            btnSubject="checkMothersite"
            btnSendAs="tab"
          >
            Check mothersite links
          </ButtonEnv>

          <ButtonEnv
            variant="blue"
            btnSubject="showShowroomConfig"
            btnSendAs="tab"
          >
            Show Showroom Config
          </ButtonEnv>
        {/if}
      </div>
    {/if}

    {#if alertBanner}
      <Alert variant="green" class="animate-fade duration-75"
        >{alertBanner.text}</Alert
      >
    {/if}
  {:else if url}
    <h2>{new URL(url).host}<br />Not Allowed</h2>
    <div class="flex flex-col gap-3">
      <p>I think it's</p>
      <div class="flex flex-row gap-3">
        <button onclick={() => setEnvironment("live")}>live</button>
        <button onclick={() => setEnvironment("perf")}>perf</button>
        <button onclick={() => setEnvironment("prod")}>prod</button>
        <button onclick={() => setEnvironment("cf#")}>classic</button>
        <button onclick={() => setEnvironment("editor.html")}>touch ui</button>
      </div>
    </div>
  {:else}
    <h2>Unknown Error Occurred</h2>
  {/if}
</div>

<div
  class="flex size-full shrink place-content-between items-end gap-2 text-white"
>
  <Link
    class="flex flex-row items-center gap-1 text-shadow-lg/20"
    href="/options.html"
  >
    <Icon src={FaSolidWrench} />
    Options
  </Link>

  <Link
    class="flex flex-row items-center gap-1 text-shadow-lg/20"
    href="https://github.com/KovalchukDanil0/aem-fixes#features"
    target="_blank"
  >
    <Icon src={FaBrandsGithub} />
    See Guide
  </Link>
</div>

<!-- TODO: implement audit mode with links to all specific site pages -->
