// src/entrypoints/popup/Popup.svelte
<script lang="ts" module>
  import { Alert, ButtonEnv, Link, Spinner } from "$components";
  import { onMessage, sendMessage } from "$lib/messaging";
  import { fullAuthorPath, propertiesPath, regexAuthor } from "$lib/storage";
  import "$styles/main.css";
  import "@fontsource/open-sans";
  import ky from "ky";
  import { Icon } from "svelte-icons-pack";
  import { FaBrandsGithub, FaSolidWrench } from "svelte-icons-pack/fa";

  interface AlertType {
    text: string;
    color: ColorProps;
  }

  const [{ url, index: tabIndex, id: tabId, status }] =
    await browser.tabs.query({
      active: true,
      currentWindow: true,
    });

  let pageLoaded = $state(false);
  let environment: EnvTypes | null = $state(null);

  let alertBanner = $state<AlertType | null>(null);

  const setEnvironment = (env: EnvTypes) => (environment = env);

  async function fetchEnvironment(tabId: number) {
    environment = await sendMessage("getEnvironment", {}, tabId).catch(
      () => null,
    );
  }

  if (status === "complete" && tabId) {
    pageLoaded = true;
    await fetchEnvironment(tabId);
  }

  browser.tabs.onUpdated.addListener(async (updatedTabId, changeInfo) => {
    if (updatedTabId !== tabId) {
      return;
    }

    if (changeInfo.status === "complete") {
      // browser.tabs.onUpdated.removeListener(listener);
      pageLoaded = true;
      await fetchEnvironment(updatedTabId);
    }

    if (changeInfo.status === "loading") {
      pageLoaded = false;
    }
  });

  onMessage("showMessage", ({ data: { text, color } }) => {
    alertBanner = { text, color };
  });

  const regexCopyContent = /\/content.+(?=\.html)/;

  function copyContent() {
    if (!url) {
      return;
    }

    const [content] = regexCopyContent.exec(url) ?? "";
    if (!content) {
      throw new Error(`copied content is ${content}`);
    }

    navigator.clipboard.writeText(content);

    alertBanner = { text: `${content} copied to clipboard`, color: "info" };
  }

  function openPropertiesTouchUI() {
    const newUrl = url?.replace(
      regexAuthor,
      `https://${fullAuthorPath}/${propertiesPath}`,
    );

    browser.tabs.create({
      url: newUrl,
      index: tabIndex + 1,
    });
  }
</script>

<div class="flex size-full grow flex-col items-center justify-center gap-5">
  {#if !pageLoaded}
    <Spinner />
    {#await ky
      .get("https://thefact.space/random")
      .json<{ text: string }>() then { text: randomFact }}
      <p class="text-shadow-lg/20">{randomFact}</p>
    {/await}
  {:else if environment}
    {#if environment === "jira"}
      <div class="flex items-center justify-center">
        <ButtonEnv variant="red" btnSubject="createWF" btnSendAs="tab"
          >Create WF</ButtonEnv
        >
      </div>
    {:else}
      <div class="hidden items-center justify-center gap-2 has-[button]:flex">
        {#if environment !== "live"}
          <ButtonEnv
            variant="green"
            btnEnv="live"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Live
          </ButtonEnv>
        {/if}

        {#if environment !== "perf"}
          <ButtonEnv
            variant="sky"
            btnEnv="perf"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Perf
          </ButtonEnv>
        {/if}

        {#if environment !== "prod"}
          <ButtonEnv
            variant="orange"
            btnEnv="prod"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Prod
          </ButtonEnv>
        {/if}

        {#if environment !== "cf#"}
          <ButtonEnv
            variant="amber"
            btnEnv="cf#"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Classic
          </ButtonEnv>
        {/if}

        {#if environment !== "editor.html"}
          <ButtonEnv
            variant="teal"
            btnEnv="editor.html"
            btnSubject="toEnvironment"
            btnSendAs="runtime"
          >
            To Touch
          </ButtonEnv>
        {/if}
      </div>

      <div
        class="hidden flex-wrap items-center justify-center gap-2 has-[button]:flex"
      >
        {#if environment === "cf#" || environment === "editor.html"}
          <ButtonEnv variant="yellow" onclick={copyContent}
            >Copy Content</ButtonEnv
          >

          <ButtonEnv variant="fuchsia" onclick={openPropertiesTouchUI}>
            Open Properties Touch UI
          </ButtonEnv>

          <ButtonEnv
            variant="violet"
            btnSubject="openInTree"
            btnSendAs="runtime"
          >
            Open In Tree
          </ButtonEnv>

          <ButtonEnv
            variant="lime"
            btnSubject="checkReferences"
            btnSendAs="tab"
          >
            Check references
          </ButtonEnv>
        {/if}

        {#if environment === "live" || environment === "perf" || environment === "prod"}
          <ButtonEnv
            variant="indigo"
            btnSubject="checkMothersite"
            btnSendAs="tab"
          >
            Check mothersite links
          </ButtonEnv>

          <ButtonEnv
            variant="blue"
            btnSubject="showShowroomConfig"
            btnSendAs="tab"
          >
            Show Showroom Config
          </ButtonEnv>
        {/if}
      </div>
    {/if}

    {#if alertBanner}
      <Alert variant="green" class="animate-fade duration-75"
        >{alertBanner.text}</Alert
      >
    {/if}
  {:else if url}
    <h2>{new URL(url).host}<br />Not Allowed</h2>
    <div class="flex flex-col gap-3">
      <p>I think it's</p>
      <div class="flex flex-row gap-3">
        <button onclick={() => setEnvironment("live")}>live</button>
        <button onclick={() => setEnvironment("perf")}>perf</button>
        <button onclick={() => setEnvironment("prod")}>prod</button>
        <button onclick={() => setEnvironment("cf#")}>classic</button>
        <button onclick={() => setEnvironment("editor.html")}>touch ui</button>
      </div>
    </div>
  {:else}
    <h2>Unknown Error Occurred</h2>
  {/if}
</div>

<div
  class="flex size-full shrink place-content-between items-end gap-2 text-white"
>
  <Link
    class="flex flex-row items-center gap-1 text-shadow-lg/20"
    href="/options.html"
  >
    <Icon src={FaSolidWrench} />
    Options
  </Link>

  <Link
    class="flex flex-row items-center gap-1 text-shadow-lg/20"
    href="https://github.com/KovalchukDanil0/aem-fixes#features"
    target="_blank"
  >
    <Icon src={FaBrandsGithub} />
    See Guide
  </Link>
</div>

<!-- TODO: implement audit mode with links to all specific site pages -->

// src/pages/Popup/Popup.tsx
import React, { useTransition } from "react";
import { useAsync } from "react-async";
import { Alert, Button, Loading } from "react-daisyui";
import { FaGithub } from "react-icons/fa";
import { IoSettingsOutline } from "react-icons/io5";
import Browser, { Tabs } from "webextension-polyfill";
import { create } from "zustand";
import UploadJsonFile from "../../containers/UploadJsonFile";
import {
  ColorProps,
  EnvTypes,
  MessageAlert,
  MessageEnv,
  classic,
  getCurrentTab,
  getFullAuthorPath,
  getLocalSavedData,
  ifAnyOfTheEnv,
  ifAuthor,
  ifClassic,
  ifJira,
  ifLive,
  ifPerf,
  ifProd,
  ifTouch,
  regexAuthor,
  touch,
} from "../../shared";

let ifAnyOfTheEnvCache = false;
let ifAuthorCache = false;
let ifClassicCache = false;
let ifJiraCache = false;
let ifLiveCache = false;
let ifPerfCache = false;
let ifProdCache = false;
let ifTouchCache = false;

let fileUploaded = true;

const regexCopyContent = /\/content.+(?=\.html)/;

type ButtonProps = {
  url: string;
};

export async function getPropertiesPath(): Promise<string> {
  const data = await getLocalSavedData();
  return data.secretSettings.propertiesPath;
}

async function cacheVariables(url: string | undefined) {
  if (!url) {
    return;
  }

  try {
    ifAnyOfTheEnvCache = await ifAnyOfTheEnv(url);
    ifAuthorCache = await ifAuthor(url);
    ifClassicCache = await ifClassic(url);
    ifJiraCache = await ifJira(url);
    ifLiveCache = await ifLive(url);
    ifPerfCache = await ifPerf(url);
    ifProdCache = await ifProd(url);
    ifTouchCache = await ifTouch(url);
  } catch {
    fileUploaded = false;
  }
}

type AlertProps = {
  text: string | undefined;
  color: ColorProps | undefined;
};

const useStateAlert = create<{
  alertProps: AlertProps | null;
  setAlertProps: (alertProps: AlertProps) => void;
}>((set) => ({
  alertProps: null,
  setAlertProps: (alertProps) =>
    set(() => ({
      alertProps: { text: alertProps.text, color: alertProps.color },
    })),
}));

function ButtonCreateWF() {
  if (!ifJiraCache) {
    return false;
  }

  return (
    <Button
      but-subject="createWF"
      but-send-as="tab"
      size="md"
      color="accent"
      id="buttonCreateWF"
      onClick={buttonOnClick}
    >
      Create WF
    </Button>
  );
}

function ButtonToLive() {
  if (!ifAnyOfTheEnvCache || ifLiveCache) {
    return false;
  }

  return (
    <Button
      but-env="live"
      but-subject="toEnvironment"
      but-send-as="runtime"
      size="md"
      id="buttonToLive"
      color="success"
      onClick={buttonOnClick}
      onAuxClick={buttonOnClick}
    >
      To Live
    </Button>
  );
}

function ButtonToPerf() {
  const [isPending, startTransition] = useTransition();

  if (!ifAnyOfTheEnvCache || ifPerfCache) {
    return false;
  }

  function pendingFunction(event: React.MouseEvent<HTMLButtonElement>) {
    startTransition(() => {
      buttonOnClick(event);
    });
  }

  return (
    <Button
      but-env="perf"
      but-subject="toEnvironment"
      but-send-as="runtime"
      size="md"
      id="buttonToPerf"
      color="info"
      onClick={pendingFunction}
      onAuxClick={pendingFunction}
    >
      To Perf {isPending && <Loading />}
    </Button>
  );
}

function ButtonToProd() {
  if (!ifAnyOfTheEnvCache || ifProdCache) {
    return false;
  }

  return (
    <Button
      but-env="prod"
      but-subject="toEnvironment"
      but-send-as="runtime"
      size="md"
      id="buttonToProd"
      color="warning"
      onClick={buttonOnClick}
      onAuxClick={buttonOnClick}
    >
      To Prod
    </Button>
  );
}

function ButtonToTouch() {
  const [isPending, startTransition] = useTransition();

  if (!ifAnyOfTheEnvCache || ifTouchCache) {
    return false;
  }

  function pendingFunction(event: React.MouseEvent<HTMLButtonElement>) {
    startTransition(() => {
      buttonOnClick(event);
    });
  }

  return (
    <Button
      but-env={touch}
      but-subject="toEnvironment"
      but-send-as="runtime"
      size="md"
      id="buttonToTouch"
      color="accent"
      onClick={pendingFunction}
      onAuxClick={pendingFunction}
    >
      To Touch {isPending && <Loading />}
    </Button>
  );
}

function ButtonToClassic() {
  if (!ifAnyOfTheEnvCache || ifClassicCache) {
    return false;
  }

  return (
    <Button
      but-env={classic}
      but-subject="toEnvironment"
      but-send-as="runtime"
      size="md"
      id="buttonToClassic"
      color="error"
      onClick={buttonOnClick}
      onAuxClick={buttonOnClick}
    >
      To Classic
    </Button>
  );
}

async function copyContent(url: string) {
  const content: string | undefined = regexCopyContent.exec(url)?.[0];

  if (!content) {
    throw new Error(`copied content is ${content}`);
  }

  navigator.clipboard.writeText(content);

  useStateAlert.setState({
    alertProps: { text: `${content} copied to clipboard`, color: "info" },
  });
}

function ButtonCopyContent({ url }: Readonly<ButtonProps>) {
  if (!ifAnyOfTheEnvCache || !ifAuthorCache) {
    return false;
  }

  return (
    <Button
      size="md"
      id="buttonCopyContent"
      color="secondary"
      onClick={() => copyContent(url)}
    >
      Copy Content
    </Button>
  );
}

function ButtonOpenPropertiesTouchUI() {
  if (!ifAnyOfTheEnvCache || !ifAuthorCache) {
    return false;
  }

  return (
    <Button
      size="md"
      id="buttonOpenPropertiesTouchUI"
      color="accent"
      onClick={openPropertiesTouchUI}
    >
      Open Properties Touch UI
    </Button>
  );
}

function ButtonOpenInTree() {
  if (!ifAnyOfTheEnvCache || !ifAuthorCache) {
    return false;
  }

  return (
    <Button
      but-subject="openInTree"
      but-send-as="runtime"
      size="md"
      id="buttonOpenInTree"
      color="success"
      onClick={buttonOnClick}
    >
      Open In Tree
    </Button>
  );
}

function ButtonCheckReferences() {
  if (!ifAnyOfTheEnvCache || !ifAuthorCache) {
    return false;
  }

  return (
    <Button
      but-subject="checkReferences"
      but-send-as="tab"
      size="md"
      id="buttonCheckReferences"
      color="error"
      onClick={buttonOnClick}
    >
      Check references
    </Button>
  );
}

function ButtonCheckMothersite() {
  if (!ifAnyOfTheEnvCache || ifAuthorCache) {
    return false;
  }

  return (
    <Button
      but-subject="checkMothersite"
      but-send-as="tab"
      size="md"
      id="buttonCheckMothersite"
      color="success"
      onClick={buttonOnClick}
    >
      Check mothersite links
    </Button>
  );
}

async function buttonOnClick(event: React.MouseEvent<HTMLButtonElement>) {
  const but: HTMLButtonElement = event.currentTarget;

  const sendAs: string | null = but.getAttribute("but-send-as");
  if (!sendAs) {
    return;
  }

  const tabs: Tabs.Tab[] = await Browser.tabs.query({
    highlighted: true,
    currentWindow: true,
  });

  const tabId = tabs[tabs.length - 1].id;
  if (!tabId) {
    throw new Error(`tabId is ${tabId}`);
  }

  const message: MessageEnv = {
    from: "popup",
    newTab: event.type !== "click",
    env: but.getAttribute("but-env") as EnvTypes,
    subject: but.getAttribute("but-subject"),
    tabs,
  };

  if (sendAs === "tab") {
    Browser.tabs.sendMessage(tabId, message);
  } else {
    Browser.runtime.sendMessage(message);
  }
}

async function openPropertiesTouchUI() {
  const tab: Tabs.Tab = await getCurrentTab();

  const fullAuthorPath = await getFullAuthorPath();

  const propertiesPath = await getPropertiesPath();

  const newUrl: string | undefined = tab.url?.replace(
    await regexAuthor(),
    `https://${fullAuthorPath}/${propertiesPath}`,
  );

  Browser.tabs.create({
    url: newUrl,
    index: tab.index + 1,
  });
}

async function initVariables(): Promise<string | undefined> {
  const url = (await getCurrentTab()).url;
  await cacheVariables(url);

  console.log(await Browser.storage.local.get());

  return url;
}

Browser.runtime.onMessage.addListener(function (
  msg: MessageAlert,
  _sender,
  _sendResponse,
) {
  if (msg.from === "popup") {
    return;
  }

  if (msg.subject === "showMessage") {
    useStateAlert.setState({
      alertProps: { text: msg.message, color: msg.color },
    });
  }
});

export default function Popup() {
  const {
    data: tabUrl,
    error,
    isPending,
  } = useAsync({ promiseFn: initVariables });

  const { alertProps } = useStateAlert();

  if (isPending) {
    return (
      <div className="grid h-44 place-items-center">
        <Loading />
      </div>
    );
  }

  if (error || !tabUrl) {
    return `Something went wrong: ${error?.message ?? "tabUrl is undefined"}`;
  }

  return (
    <div>
      {!fileUploaded && <UploadJsonFile />}

      <div className="mb-3 hidden place-content-center gap-2 has-[button]:flex">
        <ButtonCreateWF />
      </div>

      <div className="my-3 hidden place-content-center gap-2 has-[button]:flex">
        <ButtonToLive />
        <ButtonToPerf />
        <ButtonToProd />
        <ButtonToTouch />
        <ButtonToClassic />
      </div>

      <div className="my-3 hidden flex-wrap place-content-center gap-2 has-[button]:flex">
        <hr id="separator" className="my-1 h-px w-full border-0 bg-gray-200" />

        <ButtonCopyContent url={tabUrl} />
        <ButtonOpenPropertiesTouchUI />
        <ButtonOpenInTree />
        <ButtonCheckReferences />
        <ButtonCheckMothersite />
      </div>

      {alertProps && (
        <Alert className="animate-fade duration-75" status={alertProps.color}>
          {alertProps.text}
        </Alert>
      )}

      <div className="mt-10 flex place-content-between gap-2">
        <Button tag="a" href="options.html" size="sm">
          <IoSettingsOutline className="mr-2 h-5 w-5" />
          Options
        </Button>

        <Button
          tag="a"
          href="https://github.com/KovalchukDanil0/AEMFixes#features"
          target="_blank"
          size="sm"
        >
          <FaGithub className="mr-2 h-5 w-5" />
          See Guide
        </Button>
      </div>
    </div>
  );
}
