// src/entrypoints/options/Options.svelte
<script lang="ts" module>
  import type { SavedSyncData } from "$lib/storage";
  import "$styles/main.css";
  import "@fontsource/open-sans";
  import { Icon } from "svelte-icons-pack";
  import { FaSolidArrowLeft } from "svelte-icons-pack/fa";
  import { twMerge } from "tailwind-merge";

  const savedSyncDataInit = await browser.storage.sync.get<SavedSyncData>({
    disCreateWF: false,
    disMothersiteCheck: false,
    enableAutoLogin: false,
    enableFilterFix: false,
    enableFunErr: false,
  });

  const settingNames = {
    disCreateWF: "Disable Create WF Button",
    disMothersiteCheck: "Disable Mothersite Check",
    enableAutoLogin: "Enable Auto Login",
    enableFilterFix: "Enable Filter Fix in Jira",
    enableFunErr: "Enable Funny Errors",
  };

  const savedSyncData = Object.entries(savedSyncDataInit);

  function saveSyncData(data: string, value: boolean) {
    browser.storage.sync.set<SavedSyncData>({ [data]: !value });
  }
</script>

<a href="/popup.html" class="flex flex-row items-center gap-1"
  ><Icon src={FaSolidArrowLeft} />Back</a
>
<h2>AEM Fixes Settings</h2>

{#each savedSyncData as [name, value], idx}
  <div
    class={twMerge(
      "flex flex-row gap-3",
      savedSyncData.length - 1 === idx && "animate-glitch",
    )}
  >
    <label class="flex flex-row gap-1 select-none"
      >{settingNames[name as keyof typeof settingNames]}<input
        onchange={() => saveSyncData(name, value)}
        checked={value}
        type="checkbox"
      /></label
    >
  </div>
{/each}

// src/pages/Options/Options.tsx
import React from "react";
import { useAsync } from "react-async";
import { Checkbox, Loading } from "react-daisyui";
import Browser from "webextension-polyfill";
import UploadJsonFile from "../../containers/UploadJsonFile";
import { SavedSyncData, loadSavedData } from "../../shared";

const settingNames = {
  disCreateWF: "Disable create WF button",
  disMothersiteCheck: "Disable motersite check",
  enableAutoLogin: "Enable auto login",
  enableFilterFix: "Enable filter fix",
  enableFunErr: "Enable funny errors",
};

async function saveOptions(event: React.MouseEvent<HTMLInputElement>) {
  const elm = event.currentTarget;

  const data: SavedSyncData = { [elm.id]: elm.checked };
  Browser.storage.sync.set(data);
}

const initVariables = async (): Promise<SavedSyncData> => loadSavedData();

export default function Options() {
  const {
    data: savedData,
    error,
    isPending,
  } = useAsync({ promiseFn: initVariables });

  if (isPending) {
    return (
      <div className="grid h-44 place-items-center">
        <Loading />
      </div>
    );
  }

  if (error || !savedData) {
    return (
      <p>Something went wrong: {error?.message ?? "savedData is undefined"}</p>
    );
  }

  return (
    <div className="flex flex-col gap-5">
      {Object.keys(savedData).map((data) => (
        <label key={data} className="w-2/3 text-white">
          <Checkbox
            className="mr-2"
            id={data}
            onClick={saveOptions}
            defaultChecked={savedData[data as keyof typeof savedData]}
          />
          {settingNames[data as keyof typeof settingNames]}
        </label>
      ))}

      <UploadJsonFile />
    </div>
  );
}
