// src/entrypoints/options/Options.svelte
<script lang="ts" module>
  import type { SavedSyncData } from "$lib/storage";
  import "$styles/main.css";
  import "@fontsource/open-sans";
  import { Icon } from "svelte-icons-pack";
  import { FaSolidArrowLeft } from "svelte-icons-pack/fa";
  import { twMerge } from "tailwind-merge";

  const savedSyncDataInit = await browser.storage.sync.get<SavedSyncData>({
    disCreateWF: false,
    disMothersiteCheck: false,
    enableAutoLogin: false,
    enableFilterFix: false,
    enableFunErr: false,
  });

  const settingNames = {
    disCreateWF: "Disable Create WF Button",
    disMothersiteCheck: "Disable Mothersite Check",
    enableAutoLogin: "Enable Auto Login",
    enableFilterFix: "Enable Filter Fix in Jira",
    enableFunErr: "Enable Funny Errors",
  };

  const savedSyncData = Object.entries(savedSyncDataInit);

  function saveSyncData(data: string, value: boolean) {
    browser.storage.sync.set<SavedSyncData>({ [data]: !value });
  }
</script>

<a href="/popup.html" class="flex flex-row items-center gap-1"
  ><Icon src={FaSolidArrowLeft} />Back</a
>
<h2>AEM Fixes Settings</h2>

{#each savedSyncData as [name, value], idx}
  <div
    class={twMerge(
      "flex flex-row gap-3",
      savedSyncData.length - 1 === idx && "animate-glitch",
    )}
  >
    <label class="flex flex-row gap-1 select-none"
      >{settingNames[name as keyof typeof settingNames]}<input
        onchange={() => saveSyncData(name, value)}
        checked={value}
        type="checkbox"
      /></label
    >
  </div>
{/each}

// src/pages/options/Options.tsx
import { MouseEvent, ReactElement } from "react";
import { Async } from "react-async";
import { Checkbox, Loading } from "react-daisyui";
import UploadJsonFile from "src/components/UploadJsonFile";
import { loadSavedData } from "src/lib/storage";
import { SavedSyncData } from "src/lib/types";
import { storage } from "webextension-polyfill";
import "./index.scss";

const settingNames = {
  disCreateWF: "Disable create WF button",
  disMothersiteCheck: "Disable motersite check",
  enableAutoLogin: "Enable auto login",
  enableFilterFix: "Enable filter fix",
  enableFunErr: "Enable funny errors",
};

async function saveOptions({
  currentTarget: { id, checked },
}: MouseEvent<HTMLInputElement>): Promise<void> {
  const data: SavedSyncData = { [id]: checked };
  storage.sync.set(data);
}

const initVariables = async (): Promise<SavedSyncData> => loadSavedData();

export default function Options(): ReactElement {
  return (
    <Async promiseFn={initVariables}>
      <Async.Pending>
        <div className="grid h-44 place-items-center">
          <Loading />
        </div>
      </Async.Pending>
      <Async.Fulfilled>
        {(savedData: SavedSyncData) => (
          <div className="flex flex-col gap-5">
            {Object.keys(savedData).map((option) => (
              <label
                key={option}
                className="w-fit cursor-pointer text-sm text-white md:text-4xl"
              >
                <Checkbox
                  color="warning"
                  className="relative bottom-px mr-2 size-5 align-middle md:size-8"
                  id={option}
                  onClick={saveOptions}
                  defaultChecked={savedData[option as keyof typeof savedData]}
                />
                <p className="inline-block md:ml-3">
                  {settingNames[option as keyof typeof settingNames]}
                </p>
              </label>
            ))}

            <UploadJsonFile />
          </div>
        )}
      </Async.Fulfilled>
      <Async.Rejected>
        {(error) => `Something went wrong: ${error.message}`}
      </Async.Rejected>
    </Async>
  );
}
